version: "3.1"

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: asdf
      POSTGRES_DB: fazool-integration-test
      POSTGRES_HOST: postgres
      POSTGRES_USER: postgres
    ports:
      - 5432:5432